production:
  sessions:
    default:
      database: festinare_api
      hosts:
      - <%= ENV['MONGODB_DB_HOST'] || 'localhost' %>:<%= ENV['MONGODB_DB_PORT'] || 27017 %>
      username: <%= ENV['MONGODB_DB_USERNAME'] %>
      password: <%= ENV['MONGODB_DB_PASSWORD'] %>
      options:
        pool_size: <%= Integer(ENV['POOL_SIZE']) %>
        timeout: 20
        max_retries: <%= Integer(ENV['POOL_SIZE']) %>
  options:
    use_activesupport_time_zone: true
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      database: festinare_api_development
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - <%= ENV['MONGODB_DB_HOST'] || 'localhost' %>:<%= ENV['MONGODB_DB_PORT'] || 27017 %>
      options:
        pool_size: <%= Integer(ENV['POOL_SIZE']) %>
        timeout: 20
        max_retries: <%= Integer(ENV['POOL_SIZE']) %>
        # Change the default write concern. (default = { w: 1 })
        # write:
        # w: 1

        # Change the default consistency model to primary, secondary.
        # 'secondary' will send reads to secondaries, 'primary' sends everything
        # to master. (default: primary)
        # read: secondary_preferred

        # The time in seconds that Moped should wait before retrying an
        # operation on failure. (default: 0.25)
        # retry_interval: 0.25
  # Configure Mongoid specific options. (optional)
  options:
    use_activesupport_time_zone: true
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Protect id and type from mass assignment. (default: true)
    # protect_sensitive_fields: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
test:
  sessions:
    default:
      database: festinare_api_test
      hosts:
        - localhost:27017
      options:
        read: primary
        retry_interval: 1
        pool_size: <%= Integer(ENV['POOL_SIZE']) %>
        timeout: 20
        max_retries: 30
  options:
    use_activesupport_time_zone: true
